### ISSUE TITLE
Aromabackup support

### ISSUE THREAD

**Issue by inverse** [MechandMagic/Mech-and-Magic#11]
Would be awesome if the modpack could have optional at least support for Aromabackup.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287828-aroma1997s-mods-betterchests-mining-world-mod

I've added it in manually but it provides an awesome and easily to use way to backup worlds. Only really needed to modify a few settings due to path issues on windows. 

`S:location=./backup/mechmagic` - adding the .

**Comment by Cuppycake** [comment]
I have no real interest in adding Aroma Backup at this time.
