### ISSUE TITLE
Twilight Hydra missing its heads

### ISSUE THREAD

**Issue by BBgun38** [MechandMagic/Mech-and-Magic#17]
before and after the update the hydra in the twilight forest was missing his heads. Naly thinks it might be because you can capture them and use them to grief. Is that true or just a bug?

**Comment by BBgun38** [comment]
we were still able to kill him but it did take awhile to do so

**Comment by Cuppycake** [comment]
No more of this speculation crap from Naly or whoever. Don't assume from anyone that something is disabled or intentionally shut off unless you read it posted somewhere in a pack information page or told by staff. Ask staff. If they dont know, ask me. Its probably just a bug. Ill have to try to reproduce it.
