### ISSUE TITLE
NEI

### ISSUE THREAD

**Issue by Gilgreth** [MechandMagic/Mech-and-Magic#19]
When using the Rick-Click function or the "U" Key function on any NEI recipe it will severely bog down the system and eventually crash Minecraft from the server OR CTD Minecraft. A friend looked at my error log and said it was a Memory issue but that was due to NEI clogging everything up. This also effects a few other people on our server and want to know if it is a mod that is struggling or what?

**Comment by Cuppycake** [comment]
It's indeed a memory issue. With 160 mods usually loaded think about running every item in the game through a strainer on multiple levels pretty much like a clear text filter works. It gets slowed and clogged up. Looking into it but can pin point if its an exact mod derping or just sheer volume.

**Comment by Gilgreth** [comment]
I still don't understand that it is only effecting the Right-Click and "u" functions on the NEI. I can left click through everything just fine. So why does it go stupid when I try and go back a step.

**Comment by Gilgreth** [comment]
The Issue seemed to be the "Secret Doors" mod. Deactivating it on the server freed up serverside CPU, RAM, No-One is crashing, and NEI is working.

**Comment by Cuppycake** [comment]
Thanks. We will be removing the mod all together due to its horrendous resource usage, mod incompatibility that frequently corrupts chunks, and generally buginess .
