### ISSUE TITLE
Team speak is Down

### ISSUE THREAD

**Issue by usmc-Blockhead** [MechandMagic/Mech-and-Magic#20]
Team Speak Is down. thank you

**Comment by usmc-Blockhead** [comment]
No one is able to connect, is there something we should know?   

here is what it tells me when connecting:

<13:57:44> Trying to resolve hostname sgutilities.com
<13:57:48> Trying to connect to server on sgutilities.com
<13:57:54> Failed to connect to server

**Comment by Cuppycake** [comment]
This is not a forum for the community.  Only for the mod pack.  TeamSpeak will not be on again until later in the evening.

**Comment by usmc-Blockhead** [comment]
sorry...if we had one, I would use it.....LOL!  Do you need help with one?....I have been the admin for many clan and gamer forums in the past.

**Comment by Cuppycake** [comment]
Planning on it.  Just haven't had the time to build one on my server.
