### ISSUE TITLE
login crashing the server

### ISSUE THREAD

**Issue by usmc-Blockhead** [MechandMagic/Mech-and-Magic#21]
okay so I was logged in and was going to go to rivermage's house to leave him a present.  I don't remember if I hit the page in the book or not when I crashed, but then we waited for the server to come back up and it did, and as soon as I log on to it, it would crash again.  tested by having others log on and they are fine, but if I log in it will crash again.....it crashes right as it says I have logged in so not sure if I am at home or if I did end up at rivermage's base.
here is the log:
http://paste.atlauncher.com/view/d7245ab4

**Comment by usmc-Blockhead** [comment]
Update: Lucifletch went to my base and he is not crashing, so it is most likely not anything at my base.  So it might be me or something at rivermage's base, sorry I wish I paid more attention before this happened. so I knew where I was when it happened.

**Comment by GeoDiablo** [comment]
I too seem to crash the server when logging in. I will admit I was flying around in the overworld when it had crashed. Might or might not be same area. Just move me to spawn or home and I should be fine.

**Comment by Cuppycake** [comment]
Seems as if it is Rivermage's property. I won't reset any player data at the moment but will try to fix the chunk first. Please remain off the server until this is posting is updated.

**Comment by Cuppycake** [comment]
Rolled a backup of the chunk to June 2nd. Seems to cause no issues now.

**Comment by usmc-Blockhead** [comment]
Rivermage was getting kicked as well but did not know with to do about it, so the rollback did fix it for all of us.  thanks so much for the help.
