### ISSUE TITLE
Phytogenic Isolator

### ISSUE THREAD

**Issue by RiverMage** [MechandMagic/Mech-and-Magic#22]
Not sure if it's the machine itself, but the last time as well as this time, the crash happens when I right-click to cycle through the input-output.  It seems ok if I left-click through.

**Comment by Cuppycake** [comment]
What crash is this now? Again crashing the server? Or you? Details..............................

**Comment by RiverMage** [comment]
alright, it seems like whatever this crash is it's initiated on client side, but when I try to login again the crash is server side.  trying to send you the crash report, but I seem to not know what I'm doing, if rolling back my chunk is the easiest thing to do, do so.  I won't mind

**Comment by Cuppycake** [comment]
Still have yet to explain anything lol. Did the crash happen again as you logged in again or did you place something down again?

**Comment by RiverMage** [comment]
The rollback this morning worked, placed the photogenic isolator, still good, tried to reconfigure the input/output of said machine, crashed the server, trying to log back in when the server is up, crashes the server.  Hope this answers it.

**Comment by Cuppycake** [comment]
Perfect. Ill replace the file again I still have it.
