### ISSUE TITLE
Atlauncher ''Create Server'' not working

### ISSUE THREAD

**Issue by Gsdigger** [MechandMagic/Mech-and-Magic#24]
So i downloaded the server files from At launcher and ran the LaunchServer.bat but i got an error and it requested me to press a key to continue, as always. I did but nothing happened. I know how it should go: It should create a Eula file, i would set it to true and everything would be great. But here it just closes the window and creates no new files in the folder.  It works for other servers (other modpacks i mean) just not for this one. Am i missing anything or is this actually an issue? Sorry for any spelling mistakes i don't write much in English. I will post the crash report if you want it, but i may take a bit. I will try to get it as soon as possible. Also i forgot the version i am trying to run is the newest one (2.2.20).

**Comment by Cuppycake** [comment]
Yes sir can't do much without a crash report.

**Comment by Gsdigger** [comment]
http://pastebin.com/Wa1H1qF5

**Comment by Cuppycake** [comment]
Should be fixed as of version 2.2.10-1.

**Comment by Gsdigger** [comment]
Thank you so much. You don't know how happy I am that it isn't something that can't be fixed.

**Comment by Cuppycake** [comment]
No problem thanks for reporting it.

**Comment by Gsdigger** [comment]
Thanks again and keep up the good work!😁
