### ISSUE TITLE
Conflicting Recipes

### ISSUE THREAD

**Issue by Rkurnelm** [MechandMagic/Mech-and-Magic#26]
Few recipes that are conflicting with one another:
Chisel Recipes (From Chisel)
Iron now gives Mr Crayfish Knife
Diamond now gives Diamond Trowel from Botany

Heated Furnace from BuildCraft Additions
Gives Modular Furnace Core

Hope this helps,
Rk

**Comment by Cuppycake** [comment]
This will be fixed soon. Seems its only server side.

**Comment by Cuppycake** [comment]
Coal Pellets
