### ISSUE TITLE
Smeltery Crash/bug : March 6th 2015

### ISSUE THREAD

**Issue by BBgun38** [MechandMagic/Mech-and-Magic#6]
When you scroll over the lava in the smeltery controller or put lava into the seared tank you will crash your client. (this could be why some bases you can't go to if they auto inject lava into the smeltery)

**Comment by Cuppycake** [comment]
Crash report?

**Comment by BBgun38** [comment]
Here is the log, it is at the very bottom of it 
http://paste.atlauncher.com/view/398d2ba1

**Comment by Cuppycake** [comment]
Ah typical render issue lol. Forges fault. Gonna have to wait until Cauldron updates its forge version to at least 1384 before I put this fix in.

**Comment by Cuppycake** [comment]
Resolved as of version 2.2.19-2
